version: '3.7'
services:
  mysql:
    container_name: simple-mysql
    hostname: simple-mysql
    image: mariadb:10.2
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=example_root_pass
      - MYSQL_DATABASE=simple
      - MYSQL_USER=user
      - MYSQL_PASSWORD=testpass
    restart: always

  adminer:
    container_name: simple-adminer
    image: adminer:4.7-standalone
    ports:
      - 8000:8080
    environment:
      ADMINER_DEFAULT_SERVER: simple-mysql
    depends_on:
      - mysql
    restart: always

  mysql-backup:
    container_name: mysql-backup
    build: mysql-backup
    links:
      - mysql
    volumes:
      - ./backup:/backup
    environment:
      - MYSQL_HOST=simple-mysql
      - MYSQL_DATABASE=simple
      - MYSQL_USER=user
      - MYSQL_PASSWORD=testpass
      - DAYS_TO_KEEP=3
      - COMPRESSION=GZ
    restart: always
